# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "rspec"
gem "pry"
gem "nokogiri"
gem "get_process_mem"
gem "rubocop"
gem "rubocop-shopify", require: false
gem "rubocop-rspec", require: false
gem "ox"
gem "saxerator"
gem "simplecov"
gem "memory_profiler"
gem "celluloid"
